// Constantes livianas del catálogo — separadas de catalog-data.ts para no arrastrar DEFAULT_PRODUCTS en el bundle del admin

export const CATEGORIES = [
  "Cocinas y Sopletes",
  "Aerosoles",
  "Lubricantes y Químicos",
  "Pistolas de Pintar",
  "Herramientas Neumáticas",
  "Discos Abrasivos",
  "Lijas y Abrasivos",
  "Cintas Adhesivas",
  "Herramientas de Construcción",
  "Sierras y Accesorios",
  "Cepillos Industriales",
  "Brocas",
  "Llaves",
  "Destornilladores",
  "Alicates",
  "Remachadoras y Accesorios",
  "Martillos",
  "Medición",
  "Cutters y Raspadores",
  "Tijeras Industriales",
  "Abrazaderas y Aprietes",
  "Grapadoras y Pistolas",
  "Precintos y Fijación",
  "Jardín",
  "Bolsos y Organizadores",
  "Canillas y Llaves",
  "Flexibles",
  "Lubricantes y Selladores",
  "Repuestos Plomería",
  "Riego",
  "Termofusión",
  "Taladros y Atornilladores",
  "Llaves de Impacto",
  "Rotomartillos",
  "Amoladoras",
  "Pulidoras",
  "Sierras",
  "Sets y Combos",
  "Clavadoras",
  "Lijadoras",
  "Cortadoras",
  "Pistolas de Calor",
  "Soldadura",
  "Generadores",
  "Bombas",
  "Compresor y Aire",
  "Aspiradoras",
  "Cepilladoras",
  "Baterías y Cargadores",
  "Herramientas de Mano",
  "Almacenamiento",
  "Herramientas INGCO",
  "Pinturas y Accesorios",
  "Accesorios",
  "Albanileria",
  "Atornilladores",
  "Baterias y Cargadores",
  "Brocas y Accesorios",
  "Compresores y Accesorios",
  "Herramientas de Jardin",
  "Llaves y Crique",
  "Martillos y Mazas",
  "Medicion",
  "Organizacion",
  "Pinzas y Alicates",
  "Pistolas de Silicona",
  "Prensas y Criques",
  "Taladros y Rotomartillos",
  "HIDRÓFUGO",
  "LIGANTE",
  "POTENCIADOR LÁTEX",
  "INFILTRACIÓN",
  "PASTINAS EN POLVO",
  "BASE COAT NF",
  "ADHESIVO PASTA",
] as const;

export const BRANDS = [
  "MOTA",
  "SANIPLAST",
  "INGCO",
  "SIKA",
  "GAMA PINTURAS",
  "TELPLAST",
  "SINTEPLAST",
] as const;

export const APP_SETTINGS_KEY = "mota_app_settings_v1";
export const CART_KEY = "mota_cart_v1";

export const DEFAULT_APP_SETTINGS = {
  businessName: "Narom Group",
  tagline: "Distribuidor mayorista para ferreterías",
  logoText: "NRM",
  accentColor: "#F4AA24",
  currency: "ARS",
  whatsappNumber: "5492613020015",
  contactEmail: "ventas@naromgroup.com.ar",
};
